language: c
install: wget https://raw.githubusercontent.com/dsheets/ocaml-travisci-skeleton/yorick/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - PACKAGE="github" OCAML_VERSION=4.01   REVDEPS=true FORK_USER=dsheets FORK_BRANCH=yorick
  - PACKAGE="github" OCAML_VERSION=latest REVDEPS=true FORK_USER=dsheets FORK_BRANCH=yorick
